-- BaseDatos.sql
-- Script PostgreSQL para el reto bank-microservices-challenge.
-- Puede ejecutarse completo en una sola base de datos para evaluacion tecnica
-- o por secciones si se desea separar clientes_db y cuentas_db.

BEGIN;

-- =========================================================
-- MICROSERVICIO: cliente-persona-service
-- Tabla principal de clientes. Persona se modela en la misma tabla.
-- =========================================================

CREATE TABLE IF NOT EXISTS clientes (
    cliente_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    genero VARCHAR(50),
    edad INTEGER,
    identificacion VARCHAR(100) NOT NULL,
    direccion VARCHAR(255),
    telefono VARCHAR(100),
    contrasena VARCHAR(255) NOT NULL,
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_clientes_identificacion UNIQUE (identificacion),
    CONSTRAINT chk_clientes_edad CHECK (edad IS NULL OR edad >= 0)
);

CREATE INDEX IF NOT EXISTS idx_clientes_nombre
    ON clientes (nombre);

CREATE INDEX IF NOT EXISTS idx_clientes_estado
    ON clientes (estado);

-- =========================================================
-- MICROSERVICIO: cuenta-movimiento-service
-- Snapshot local del cliente para validacion asincronica.
-- =========================================================

CREATE TABLE IF NOT EXISTS cliente_snapshot (
    cliente_id BIGINT PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    identificacion VARCHAR(100) NOT NULL,
    estado BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS idx_cliente_snapshot_identificacion
    ON cliente_snapshot (identificacion);

CREATE INDEX IF NOT EXISTS idx_cliente_snapshot_estado
    ON cliente_snapshot (estado);

-- Cuentas asociadas al cliente validado localmente.
CREATE TABLE IF NOT EXISTS cuentas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_cuenta VARCHAR(50) NOT NULL,
    tipo_cuenta VARCHAR(20) NOT NULL,
    saldo_inicial NUMERIC(19, 2) NOT NULL,
    saldo_disponible NUMERIC(19, 2) NOT NULL,
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    cliente_id BIGINT NOT NULL,
    CONSTRAINT uq_cuentas_numero_cuenta UNIQUE (numero_cuenta),
    CONSTRAINT fk_cuentas_cliente_snapshot
        FOREIGN KEY (cliente_id)
        REFERENCES cliente_snapshot (cliente_id),
    CONSTRAINT chk_cuentas_tipo_cuenta
        CHECK (tipo_cuenta IN ('AHORRO', 'CORRIENTE')),
    CONSTRAINT chk_cuentas_saldo_inicial
        CHECK (saldo_inicial >= 0),
    CONSTRAINT chk_cuentas_saldo_disponible
        CHECK (saldo_disponible >= 0)
);

CREATE INDEX IF NOT EXISTS idx_cuentas_cliente_id
    ON cuentas (cliente_id);

CREATE INDEX IF NOT EXISTS idx_cuentas_estado
    ON cuentas (estado);

-- Movimientos contables aplicados sobre cuentas.
CREATE TABLE IF NOT EXISTS movimientos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha TIMESTAMP NOT NULL,
    tipo_movimiento VARCHAR(20) NOT NULL,
    valor NUMERIC(19, 2) NOT NULL,
    saldo NUMERIC(19, 2) NOT NULL,
    cuenta_id BIGINT NOT NULL,
    CONSTRAINT fk_movimientos_cuenta
        FOREIGN KEY (cuenta_id)
        REFERENCES cuentas (id),
    CONSTRAINT chk_movimientos_tipo
        CHECK (tipo_movimiento IN ('DEPOSITO', 'RETIRO')),
    CONSTRAINT chk_movimientos_valor
        CHECK (valor <> 0),
    CONSTRAINT chk_movimientos_saldo
        CHECK (saldo >= 0)
);

CREATE INDEX IF NOT EXISTS idx_movimientos_cuenta_id
    ON movimientos (cuenta_id);

CREATE INDEX IF NOT EXISTS idx_movimientos_fecha
    ON movimientos (fecha);

CREATE INDEX IF NOT EXISTS idx_movimientos_cuenta_fecha
    ON movimientos (cuenta_id, fecha);

COMMIT;
