spring:
  application:
    name: cliente-persona-service
  datasource:
    url: ${CLIENTES_DB_URL:jdbc:postgresql://localhost:5433/clientes_db}
    username: ${CLIENTES_DB_USERNAME:clientes_user}
    password: ${CLIENTES_DB_PASSWORD:clientes_pass}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    open-in-view: false
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
  health:
    db:
      enabled: true
    rabbit:
      enabled: true

server:
  port: ${CLIENTE_PERSONA_PORT:8081}
