spring:
  application:
    name: cuenta-movimiento-service
  datasource:
    url: ${CUENTAS_DB_URL:jdbc:postgresql://localhost:5434/cuentas_db}
    username: ${CUENTAS_DB_USERNAME:cuentas_user}
    password: ${CUENTAS_DB_PASSWORD:cuentas_pass}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    open-in-view: false
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
  health:
    db:
      enabled: true
    rabbit:
      enabled: true

server:
  port: ${CUENTA_MOVIMIENTO_PORT:8082}
